version: 2
jobs:
  build:
    docker:
      - image: docker:git
    working_directory: /src
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # build and run tests
      - run:
          name: build and run tests
          command: |
            docker build -t sift .
      - deploy:
          name: push docker image
          command: |
            if [ "$ {CIRCLE_BRANCH}" == "master" ]; then
              TAG=0.$CIRCLE_BUILD_NUM
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag sift "maximz/sift:${TAG}"
              docker push "maximz/sift:${TAG}"
            fi